// Code generated by MockGen. DO NOT EDIT.
// Source: quiz-log/repository (interfaces: QuestionRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_question_repository.go -package=mocks quiz-log/repository QuestionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"quiz-log/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuestionRepository is a mock of QuestionRepository interface.
type MockQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepositoryMockRecorder
	isgomock struct{}
}

// MockQuestionRepositoryMockRecorder is the mock recorder for MockQuestionRepository.
type MockQuestionRepositoryMockRecorder struct {
	mock *MockQuestionRepository
}

// NewMockQuestionRepository creates a new mock instance.
func NewMockQuestionRepository(ctrl *gomock.Controller) *MockQuestionRepository {
	mock := &MockQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepository) EXPECT() *MockQuestionRepositoryMockRecorder {
	return m.recorder
}

// AssociateTags mocks base method.
func (m *MockQuestionRepository) AssociateTags(ctx context.Context, questionID int, tagIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssociateTags", ctx, questionID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssociateTags indicates an expected call of AssociateTags.
func (mr *MockQuestionRepositoryMockRecorder) AssociateTags(ctx, questionID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssociateTags", reflect.TypeOf((*MockQuestionRepository)(nil).AssociateTags), ctx, questionID, tagIDs)
}

// ClearTags mocks base method.
func (m *MockQuestionRepository) ClearTags(ctx context.Context, questionID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearTags", ctx, questionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearTags indicates an expected call of ClearTags.
func (mr *MockQuestionRepositoryMockRecorder) ClearTags(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearTags", reflect.TypeOf((*MockQuestionRepository)(nil).ClearTags), ctx, questionID)
}

// Create mocks base method.
func (m *MockQuestionRepository) Create(ctx context.Context, quizID, questionType, content string, options []string, correctAnswer string, explanation *string, difficulty string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, quizID, questionType, content, options, correctAnswer, explanation, difficulty)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockQuestionRepositoryMockRecorder) Create(ctx, quizID, questionType, content, options, correctAnswer, explanation, difficulty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuestionRepository)(nil).Create), ctx, quizID, questionType, content, options, correctAnswer, explanation, difficulty)
}

// Delete mocks base method.
func (m *MockQuestionRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQuestionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuestionRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockQuestionRepository) FindAll(ctx context.Context, quizID *int) ([]*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, quizID)
	ret0, _ := ret[0].([]*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockQuestionRepositoryMockRecorder) FindAll(ctx, quizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockQuestionRepository)(nil).FindAll), ctx, quizID)
}

// FindByID mocks base method.
func (m *MockQuestionRepository) FindByID(ctx context.Context, id int) (*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockQuestionRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockQuestionRepository)(nil).FindByID), ctx, id)
}

// FindTagsByQuestionID mocks base method.
func (m *MockQuestionRepository) FindTagsByQuestionID(ctx context.Context, questionID int) ([]*models.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTagsByQuestionID", ctx, questionID)
	ret0, _ := ret[0].([]*models.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTagsByQuestionID indicates an expected call of FindTagsByQuestionID.
func (mr *MockQuestionRepositoryMockRecorder) FindTagsByQuestionID(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTagsByQuestionID", reflect.TypeOf((*MockQuestionRepository)(nil).FindTagsByQuestionID), ctx, questionID)
}

// FindWrongQuestions mocks base method.
func (m *MockQuestionRepository) FindWrongQuestions(ctx context.Context) ([]*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWrongQuestions", ctx)
	ret0, _ := ret[0].([]*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWrongQuestions indicates an expected call of FindWrongQuestions.
func (mr *MockQuestionRepositoryMockRecorder) FindWrongQuestions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWrongQuestions", reflect.TypeOf((*MockQuestionRepository)(nil).FindWrongQuestions), ctx)
}

// Update mocks base method.
func (m *MockQuestionRepository) Update(ctx context.Context, id int, questionType, content *string, options []string, correctAnswer, explanation, difficulty *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, questionType, content, options, correctAnswer, explanation, difficulty)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuestionRepositoryMockRecorder) Update(ctx, id, questionType, content, options, correctAnswer, explanation, difficulty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuestionRepository)(nil).Update), ctx, id, questionType, content, options, correctAnswer, explanation, difficulty)
}
