// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DATA-DOG/go-sqlmock (interfaces: Sqlmock)
//
// Generated by this command:
//
//	mockgen -destination=repository/mocks/mock_sqlmock.go -package=mocks github.com/DATA-DOG/go-sqlmock Sqlmock
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	sqlmock "github.com/DATA-DOG/go-sqlmock"
	gomock "go.uber.org/mock/gomock"
)

// MockSqlmock is a mock of Sqlmock interface.
type MockSqlmock struct {
	ctrl     *gomock.Controller
	recorder *MockSqlmockMockRecorder
	isgomock struct{}
}

// MockSqlmockMockRecorder is the mock recorder for MockSqlmock.
type MockSqlmockMockRecorder struct {
	mock *MockSqlmock
}

// NewMockSqlmock creates a new mock instance.
func NewMockSqlmock(ctrl *gomock.Controller) *MockSqlmock {
	mock := &MockSqlmock{ctrl: ctrl}
	mock.recorder = &MockSqlmockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSqlmock) EXPECT() *MockSqlmockMockRecorder {
	return m.recorder
}

// ExpectBegin mocks base method.
func (m *MockSqlmock) ExpectBegin() *sqlmock.ExpectedBegin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectBegin")
	ret0, _ := ret[0].(*sqlmock.ExpectedBegin)
	return ret0
}

// ExpectBegin indicates an expected call of ExpectBegin.
func (mr *MockSqlmockMockRecorder) ExpectBegin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectBegin", reflect.TypeOf((*MockSqlmock)(nil).ExpectBegin))
}

// ExpectClose mocks base method.
func (m *MockSqlmock) ExpectClose() *sqlmock.ExpectedClose {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectClose")
	ret0, _ := ret[0].(*sqlmock.ExpectedClose)
	return ret0
}

// ExpectClose indicates an expected call of ExpectClose.
func (mr *MockSqlmockMockRecorder) ExpectClose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectClose", reflect.TypeOf((*MockSqlmock)(nil).ExpectClose))
}

// ExpectCommit mocks base method.
func (m *MockSqlmock) ExpectCommit() *sqlmock.ExpectedCommit {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectCommit")
	ret0, _ := ret[0].(*sqlmock.ExpectedCommit)
	return ret0
}

// ExpectCommit indicates an expected call of ExpectCommit.
func (mr *MockSqlmockMockRecorder) ExpectCommit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectCommit", reflect.TypeOf((*MockSqlmock)(nil).ExpectCommit))
}

// ExpectExec mocks base method.
func (m *MockSqlmock) ExpectExec(expectedSQL string) *sqlmock.ExpectedExec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectExec", expectedSQL)
	ret0, _ := ret[0].(*sqlmock.ExpectedExec)
	return ret0
}

// ExpectExec indicates an expected call of ExpectExec.
func (mr *MockSqlmockMockRecorder) ExpectExec(expectedSQL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectExec", reflect.TypeOf((*MockSqlmock)(nil).ExpectExec), expectedSQL)
}

// ExpectPing mocks base method.
func (m *MockSqlmock) ExpectPing() *sqlmock.ExpectedPing {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectPing")
	ret0, _ := ret[0].(*sqlmock.ExpectedPing)
	return ret0
}

// ExpectPing indicates an expected call of ExpectPing.
func (mr *MockSqlmockMockRecorder) ExpectPing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectPing", reflect.TypeOf((*MockSqlmock)(nil).ExpectPing))
}

// ExpectPrepare mocks base method.
func (m *MockSqlmock) ExpectPrepare(expectedSQL string) *sqlmock.ExpectedPrepare {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectPrepare", expectedSQL)
	ret0, _ := ret[0].(*sqlmock.ExpectedPrepare)
	return ret0
}

// ExpectPrepare indicates an expected call of ExpectPrepare.
func (mr *MockSqlmockMockRecorder) ExpectPrepare(expectedSQL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectPrepare", reflect.TypeOf((*MockSqlmock)(nil).ExpectPrepare), expectedSQL)
}

// ExpectQuery mocks base method.
func (m *MockSqlmock) ExpectQuery(expectedSQL string) *sqlmock.ExpectedQuery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectQuery", expectedSQL)
	ret0, _ := ret[0].(*sqlmock.ExpectedQuery)
	return ret0
}

// ExpectQuery indicates an expected call of ExpectQuery.
func (mr *MockSqlmockMockRecorder) ExpectQuery(expectedSQL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectQuery", reflect.TypeOf((*MockSqlmock)(nil).ExpectQuery), expectedSQL)
}

// ExpectRollback mocks base method.
func (m *MockSqlmock) ExpectRollback() *sqlmock.ExpectedRollback {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectRollback")
	ret0, _ := ret[0].(*sqlmock.ExpectedRollback)
	return ret0
}

// ExpectRollback indicates an expected call of ExpectRollback.
func (mr *MockSqlmockMockRecorder) ExpectRollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectRollback", reflect.TypeOf((*MockSqlmock)(nil).ExpectRollback))
}

// ExpectationsWereMet mocks base method.
func (m *MockSqlmock) ExpectationsWereMet() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectationsWereMet")
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpectationsWereMet indicates an expected call of ExpectationsWereMet.
func (mr *MockSqlmockMockRecorder) ExpectationsWereMet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectationsWereMet", reflect.TypeOf((*MockSqlmock)(nil).ExpectationsWereMet))
}

// MatchExpectationsInOrder mocks base method.
func (m *MockSqlmock) MatchExpectationsInOrder(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MatchExpectationsInOrder", arg0)
}

// MatchExpectationsInOrder indicates an expected call of MatchExpectationsInOrder.
func (mr *MockSqlmockMockRecorder) MatchExpectationsInOrder(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchExpectationsInOrder", reflect.TypeOf((*MockSqlmock)(nil).MatchExpectationsInOrder), arg0)
}

// NewColumn mocks base method.
func (m *MockSqlmock) NewColumn(name string) *sqlmock.Column {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewColumn", name)
	ret0, _ := ret[0].(*sqlmock.Column)
	return ret0
}

// NewColumn indicates an expected call of NewColumn.
func (mr *MockSqlmockMockRecorder) NewColumn(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewColumn", reflect.TypeOf((*MockSqlmock)(nil).NewColumn), name)
}

// NewRows mocks base method.
func (m *MockSqlmock) NewRows(columns []string) *sqlmock.Rows {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRows", columns)
	ret0, _ := ret[0].(*sqlmock.Rows)
	return ret0
}

// NewRows indicates an expected call of NewRows.
func (mr *MockSqlmockMockRecorder) NewRows(columns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRows", reflect.TypeOf((*MockSqlmock)(nil).NewRows), columns)
}

// NewRowsWithColumnDefinition mocks base method.
func (m *MockSqlmock) NewRowsWithColumnDefinition(columns ...*sqlmock.Column) *sqlmock.Rows {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range columns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewRowsWithColumnDefinition", varargs...)
	ret0, _ := ret[0].(*sqlmock.Rows)
	return ret0
}

// NewRowsWithColumnDefinition indicates an expected call of NewRowsWithColumnDefinition.
func (mr *MockSqlmockMockRecorder) NewRowsWithColumnDefinition(columns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRowsWithColumnDefinition", reflect.TypeOf((*MockSqlmock)(nil).NewRowsWithColumnDefinition), columns...)
}
