// Code generated by MockGen. DO NOT EDIT.
// Source: quiz-log/repository (interfaces: AttemptRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_attempt_repository.go -package=mocks quiz-log/repository AttemptRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	db "quiz-log/db"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAttemptRepository is a mock of AttemptRepository interface.
type MockAttemptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAttemptRepositoryMockRecorder
	isgomock struct{}
}

// MockAttemptRepositoryMockRecorder is the mock recorder for MockAttemptRepository.
type MockAttemptRepositoryMockRecorder struct {
	mock *MockAttemptRepository
}

// NewMockAttemptRepository creates a new mock instance.
func NewMockAttemptRepository(ctrl *gomock.Controller) *MockAttemptRepository {
	mock := &MockAttemptRepository{ctrl: ctrl}
	mock.recorder = &MockAttemptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttemptRepository) EXPECT() *MockAttemptRepositoryMockRecorder {
	return m.recorder
}

// CountQuestionsByQuizID mocks base method.
func (m *MockAttemptRepository) CountQuestionsByQuizID(ctx context.Context, quizID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountQuestionsByQuizID", ctx, quizID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountQuestionsByQuizID indicates an expected call of CountQuestionsByQuizID.
func (mr *MockAttemptRepositoryMockRecorder) CountQuestionsByQuizID(ctx, quizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountQuestionsByQuizID", reflect.TypeOf((*MockAttemptRepository)(nil).CountQuestionsByQuizID), ctx, quizID)
}

// Create mocks base method.
func (m *MockAttemptRepository) Create(ctx context.Context, quizID int, startedAt, completedAt time.Time, score, totalQuestions int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, quizID, startedAt, completedAt, score, totalQuestions)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAttemptRepositoryMockRecorder) Create(ctx, quizID, startedAt, completedAt, score, totalQuestions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAttemptRepository)(nil).Create), ctx, quizID, startedAt, completedAt, score, totalQuestions)
}

// CreateAnswer mocks base method.
func (m *MockAttemptRepository) CreateAnswer(ctx context.Context, attemptID, questionID int, userAnswer string, isCorrect bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnswer", ctx, attemptID, questionID, userAnswer, isCorrect)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAnswer indicates an expected call of CreateAnswer.
func (mr *MockAttemptRepositoryMockRecorder) CreateAnswer(ctx, attemptID, questionID, userAnswer, isCorrect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnswer", reflect.TypeOf((*MockAttemptRepository)(nil).CreateAnswer), ctx, attemptID, questionID, userAnswer, isCorrect)
}

// FindAll mocks base method.
func (m *MockAttemptRepository) FindAll(ctx context.Context, quizID *int) ([]*db.Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, quizID)
	ret0, _ := ret[0].([]*db.Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockAttemptRepositoryMockRecorder) FindAll(ctx, quizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockAttemptRepository)(nil).FindAll), ctx, quizID)
}

// FindAnswersByAttemptID mocks base method.
func (m *MockAttemptRepository) FindAnswersByAttemptID(ctx context.Context, attemptID int) ([]*db.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAnswersByAttemptID", ctx, attemptID)
	ret0, _ := ret[0].([]*db.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAnswersByAttemptID indicates an expected call of FindAnswersByAttemptID.
func (mr *MockAttemptRepositoryMockRecorder) FindAnswersByAttemptID(ctx, attemptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAnswersByAttemptID", reflect.TypeOf((*MockAttemptRepository)(nil).FindAnswersByAttemptID), ctx, attemptID)
}

// FindByID mocks base method.
func (m *MockAttemptRepository) FindByID(ctx context.Context, attemptID int) (*db.Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, attemptID)
	ret0, _ := ret[0].(*db.Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAttemptRepositoryMockRecorder) FindByID(ctx, attemptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAttemptRepository)(nil).FindByID), ctx, attemptID)
}

// GetCorrectAnswer mocks base method.
func (m *MockAttemptRepository) GetCorrectAnswer(ctx context.Context, questionID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCorrectAnswer", ctx, questionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCorrectAnswer indicates an expected call of GetCorrectAnswer.
func (mr *MockAttemptRepositoryMockRecorder) GetCorrectAnswer(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCorrectAnswer", reflect.TypeOf((*MockAttemptRepository)(nil).GetCorrectAnswer), ctx, questionID)
}

// UpdateScore mocks base method.
func (m *MockAttemptRepository) UpdateScore(ctx context.Context, attemptID, score int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScore", ctx, attemptID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScore indicates an expected call of UpdateScore.
func (mr *MockAttemptRepositoryMockRecorder) UpdateScore(ctx, attemptID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScore", reflect.TypeOf((*MockAttemptRepository)(nil).UpdateScore), ctx, attemptID, score)
}
