// Code generated by MockGen. DO NOT EDIT.
// Source: quiz-log/repository (interfaces: StatisticsRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_statistics_repository.go -package=mocks quiz-log/repository StatisticsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	repository "quiz-log/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStatisticsRepository is a mock of StatisticsRepository interface.
type MockStatisticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatisticsRepositoryMockRecorder
	isgomock struct{}
}

// MockStatisticsRepositoryMockRecorder is the mock recorder for MockStatisticsRepository.
type MockStatisticsRepositoryMockRecorder struct {
	mock *MockStatisticsRepository
}

// NewMockStatisticsRepository creates a new mock instance.
func NewMockStatisticsRepository(ctrl *gomock.Controller) *MockStatisticsRepository {
	mock := &MockStatisticsRepository{ctrl: ctrl}
	mock.recorder = &MockStatisticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatisticsRepository) EXPECT() *MockStatisticsRepositoryMockRecorder {
	return m.recorder
}

// CalculateAverageScore mocks base method.
func (m *MockStatisticsRepository) CalculateAverageScore(ctx context.Context) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateAverageScore", ctx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateAverageScore indicates an expected call of CalculateAverageScore.
func (mr *MockStatisticsRepositoryMockRecorder) CalculateAverageScore(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateAverageScore", reflect.TypeOf((*MockStatisticsRepository)(nil).CalculateAverageScore), ctx)
}

// CountTotalAttempts mocks base method.
func (m *MockStatisticsRepository) CountTotalAttempts(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotalAttempts", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotalAttempts indicates an expected call of CountTotalAttempts.
func (mr *MockStatisticsRepositoryMockRecorder) CountTotalAttempts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotalAttempts", reflect.TypeOf((*MockStatisticsRepository)(nil).CountTotalAttempts), ctx)
}

// GetCategoryStats mocks base method.
func (m *MockStatisticsRepository) GetCategoryStats(ctx context.Context) ([]*repository.CategoryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryStats", ctx)
	ret0, _ := ret[0].([]*repository.CategoryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryStats indicates an expected call of GetCategoryStats.
func (mr *MockStatisticsRepositoryMockRecorder) GetCategoryStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryStats", reflect.TypeOf((*MockStatisticsRepository)(nil).GetCategoryStats), ctx)
}
