// Code generated by MockGen. DO NOT EDIT.
// Source: quiz-log/repository (interfaces: QuizRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_quiz_repository.go -package=mocks quiz-log/repository QuizRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"quiz-log/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuizRepository is a mock of QuizRepository interface.
type MockQuizRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuizRepositoryMockRecorder
	isgomock struct{}
}

// MockQuizRepositoryMockRecorder is the mock recorder for MockQuizRepository.
type MockQuizRepositoryMockRecorder struct {
	mock *MockQuizRepository
}

// NewMockQuizRepository creates a new mock instance.
func NewMockQuizRepository(ctrl *gomock.Controller) *MockQuizRepository {
	mock := &MockQuizRepository{ctrl: ctrl}
	mock.recorder = &MockQuizRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuizRepository) EXPECT() *MockQuizRepositoryMockRecorder {
	return m.recorder
}

// AssociateTags mocks base method.
func (m *MockQuizRepository) AssociateTags(ctx context.Context, quizID int, tagIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssociateTags", ctx, quizID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssociateTags indicates an expected call of AssociateTags.
func (mr *MockQuizRepositoryMockRecorder) AssociateTags(ctx, quizID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssociateTags", reflect.TypeOf((*MockQuizRepository)(nil).AssociateTags), ctx, quizID, tagIDs)
}

// ClearTags mocks base method.
func (m *MockQuizRepository) ClearTags(ctx context.Context, quizID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearTags", ctx, quizID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearTags indicates an expected call of ClearTags.
func (mr *MockQuizRepositoryMockRecorder) ClearTags(ctx, quizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearTags", reflect.TypeOf((*MockQuizRepository)(nil).ClearTags), ctx, quizID)
}

// Create mocks base method.
func (m *MockQuizRepository) Create(ctx context.Context, title string, description *string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, title, description)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockQuizRepositoryMockRecorder) Create(ctx, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuizRepository)(nil).Create), ctx, title, description)
}

// Delete mocks base method.
func (m *MockQuizRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQuizRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuizRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockQuizRepository) FindAll(ctx context.Context) ([]*models.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*models.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockQuizRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockQuizRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockQuizRepository) FindByID(ctx context.Context, id int) (*models.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockQuizRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockQuizRepository)(nil).FindByID), ctx, id)
}

// FindQuestionsByQuizID mocks base method.
func (m *MockQuizRepository) FindQuestionsByQuizID(ctx context.Context, quizID int) ([]*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindQuestionsByQuizID", ctx, quizID)
	ret0, _ := ret[0].([]*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindQuestionsByQuizID indicates an expected call of FindQuestionsByQuizID.
func (mr *MockQuizRepositoryMockRecorder) FindQuestionsByQuizID(ctx, quizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindQuestionsByQuizID", reflect.TypeOf((*MockQuizRepository)(nil).FindQuestionsByQuizID), ctx, quizID)
}

// FindQuestionsByQuizIDs mocks base method.
func (m *MockQuizRepository) FindQuestionsByQuizIDs(ctx context.Context, quizIDs []int) (map[int][]*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindQuestionsByQuizIDs", ctx, quizIDs)
	ret0, _ := ret[0].(map[int][]*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindQuestionsByQuizIDs indicates an expected call of FindQuestionsByQuizIDs.
func (mr *MockQuizRepositoryMockRecorder) FindQuestionsByQuizIDs(ctx, quizIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindQuestionsByQuizIDs", reflect.TypeOf((*MockQuizRepository)(nil).FindQuestionsByQuizIDs), ctx, quizIDs)
}

// FindTagsByQuizID mocks base method.
func (m *MockQuizRepository) FindTagsByQuizID(ctx context.Context, quizID int) ([]*models.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTagsByQuizID", ctx, quizID)
	ret0, _ := ret[0].([]*models.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTagsByQuizID indicates an expected call of FindTagsByQuizID.
func (mr *MockQuizRepositoryMockRecorder) FindTagsByQuizID(ctx, quizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTagsByQuizID", reflect.TypeOf((*MockQuizRepository)(nil).FindTagsByQuizID), ctx, quizID)
}

// FindTagsByQuizIDs mocks base method.
func (m *MockQuizRepository) FindTagsByQuizIDs(ctx context.Context, quizIDs []int) (map[int][]*models.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTagsByQuizIDs", ctx, quizIDs)
	ret0, _ := ret[0].(map[int][]*models.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTagsByQuizIDs indicates an expected call of FindTagsByQuizIDs.
func (mr *MockQuizRepositoryMockRecorder) FindTagsByQuizIDs(ctx, quizIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTagsByQuizIDs", reflect.TypeOf((*MockQuizRepository)(nil).FindTagsByQuizIDs), ctx, quizIDs)
}

// Update mocks base method.
func (m *MockQuizRepository) Update(ctx context.Context, id int, title, description *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, title, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuizRepositoryMockRecorder) Update(ctx, id, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuizRepository)(nil).Update), ctx, id, title, description)
}
