package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"quiz-log/graph/model"
)

// SubmitAttempt is the resolver for the submitAttempt field.
func (r *mutationResolver) SubmitAttempt(ctx context.Context, input model.SubmitAttemptInput) (*model.AttemptResult, error) {
	return r.AttemptService.SubmitAttempt(ctx, input)
}

// Attempts is the resolver for the attempts field.
func (r *queryResolver) Attempts(ctx context.Context, quizID *string) ([]*model.Attempt, error) {
	return r.AttemptService.GetAttempts(ctx, quizID)
}
