package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"quiz-log/graph/model"
)

// SubmitAttempt is the resolver for the submitAttempt field.
func (r *mutationResolver) SubmitAttempt(ctx context.Context, input model.SubmitAttemptInput) (*model.AttemptResult, error) {
	return r.AttemptService.SubmitAttempt(ctx, input)
}

// Attempts is the resolver for the attempts field.
func (r *queryResolver) Attempts(ctx context.Context, quizID *string) ([]*model.Attempt, error) {
	return r.AttemptService.GetAttempts(ctx, quizID)
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *attemptResolver) Answers(ctx context.Context, obj *model.Attempt) ([]*model.Answer, error) {
	return r.AttemptService.GetAnswersByAttemptID(ctx, obj.ID)
}
func (r *Resolver) Attempt() graph.AttemptResolver { return &attemptResolver{r} }
type attemptResolver struct{ *Resolver }
*/
