package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"quiz-log/graph/model"
)

// CreateQuestion is the resolver for the createQuestion field.
func (r *mutationResolver) CreateQuestion(ctx context.Context, input model.CreateQuestionInput) (*model.Question, error) {
	return r.QuestionService.CreateQuestion(ctx, input)
}

// UpdateQuestion is the resolver for the updateQuestion field.
func (r *mutationResolver) UpdateQuestion(ctx context.Context, id string, input model.UpdateQuestionInput) (*model.Question, error) {
	return r.QuestionService.UpdateQuestion(ctx, id, input)
}

// DeleteQuestion is the resolver for the deleteQuestion field.
func (r *mutationResolver) DeleteQuestion(ctx context.Context, id string) (bool, error) {
	return r.QuestionService.DeleteQuestion(ctx, id)
}

// ImportQuestions is the resolver for the importQuestions field.
func (r *mutationResolver) ImportQuestions(ctx context.Context, data string) ([]*model.Question, error) {
	return r.QuestionService.ImportQuestions(ctx, data)
}

// ExportQuestions is the resolver for the exportQuestions field.
func (r *mutationResolver) ExportQuestions(ctx context.Context, quizID *string) (string, error) {
	return r.QuestionService.ExportQuestions(ctx, quizID)
}

// Questions is the resolver for the questions field.
func (r *queryResolver) Questions(ctx context.Context, quizID *string) ([]*model.Question, error) {
	return r.QuestionService.GetAllQuestions(ctx, quizID)
}

// Question is the resolver for the question field.
func (r *queryResolver) Question(ctx context.Context, id string) (*model.Question, error) {
	return r.QuestionService.GetQuestionByID(ctx, id)
}

// WrongQuestions is the resolver for the wrongQuestions field.
func (r *queryResolver) WrongQuestions(ctx context.Context) ([]*model.Question, error) {
	return r.QuestionService.GetWrongQuestions(ctx)
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *questionResolver) Tags(ctx context.Context, obj *model.Question) ([]*model.Tag, error) {
	return r.QuestionService.GetTagsByQuestionID(ctx, obj.ID)
}
func (r *Resolver) Question() graph.QuestionResolver { return &questionResolver{r} }
type questionResolver struct{ *Resolver }
*/
