package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"strconv"

	"quiz-log/dataloader"
	"quiz-log/graph"
	"quiz-log/graph/model"
)

// CreateQuiz is the resolver for the createQuiz field.
func (r *mutationResolver) CreateQuiz(ctx context.Context, input model.CreateQuizInput) (*model.Quiz, error) {
	return r.QuizService.CreateQuiz(ctx, input)
}

// UpdateQuiz is the resolver for the updateQuiz field.
func (r *mutationResolver) UpdateQuiz(ctx context.Context, id string, input model.UpdateQuizInput) (*model.Quiz, error) {
	return r.QuizService.UpdateQuiz(ctx, id, input)
}

// DeleteQuiz is the resolver for the deleteQuiz field.
func (r *mutationResolver) DeleteQuiz(ctx context.Context, id string) (bool, error) {
	return r.QuizService.DeleteQuiz(ctx, id)
}

// Quizzes is the resolver for the quizzes field.
func (r *queryResolver) Quizzes(ctx context.Context) ([]*model.Quiz, error) {
	return r.QuizService.GetAllQuizzes(ctx)
}

// Quiz is the resolver for the quiz field.
func (r *queryResolver) Quiz(ctx context.Context, id string) (*model.Quiz, error) {
	return r.QuizService.GetQuizByID(ctx, id)
}

// Questions is the resolver for the questions field on Quiz type.
func (r *quizResolver) Questions(ctx context.Context, obj *model.Quiz) ([]*model.Question, error) {
	loaders := dataloader.For(ctx)
	quizID, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, err
	}
	return loaders.QuestionsByQuizID.Load(ctx, quizID)()
}

// Tags is the resolver for the tags field on Quiz type.
func (r *quizResolver) Tags(ctx context.Context, obj *model.Quiz) ([]*model.Tag, error) {
	loaders := dataloader.For(ctx)
	quizID, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, err
	}
	return loaders.TagsByQuizID.Load(ctx, quizID)()
}

// Quiz returns graph.QuizResolver implementation.
func (r *Resolver) Quiz() graph.QuizResolver { return &quizResolver{r} }

type quizResolver struct{ *Resolver }
