package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	
	"quiz-log/graph/model"
)

// Statistics is the resolver for the statistics field.
func (r *queryResolver) Statistics(ctx context.Context) (*model.Statistics, error) {
	return r.StatisticsService.GetStatistics(ctx)
}
